name: Build Native

on:
  push:
    branches: [ main ]
    tags: [ '*' ]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ayltai/setup-graalvm@v1
        with:
          java-version: 17
          graalvm-version: 22.2.0
          native-image: true
      - name: Build with Maven
        run: mvn -B clean install -Dnative --file pom.xml
      - name: Move artifacts
        run: mkdir target/linux-native && mv target/sockiopath*runner target/linux-native
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: linux-native
          path: target/linux-native

#  windows:
#    runs-on: windows-latest
#    steps:
#      - uses: actions/checkout@v2
#      - uses: ilammy/msvc-dev-cmd@v1.5.0
#      - uses: microsoft/setup-msbuild@v1
#      - uses: ayltai/setup-graalvm@v1
#        with:
#          java-version: 17
#          graalvm-version: 22.2.0
#          native-image: true
#      - name: Build with Maven
#        run: mvn -B clean install -Dnative --file pom.xml
#        shell: powershell
#      - name: Move artifacts
#        run: mkdir target/windows-native && mv target/sockiopath*runner target/windows-native
#      - name: Upload artifacts
#        uses: actions/upload-artifact@v2
#        with:
#          name: windows-native
#          path: target/windows-native

  mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ayltai/setup-graalvm@v1
        with:
          java-version: 17
          graalvm-version: 22.2.0
          native-image: true
      - name: Build with Maven
        run: mvn -DskipTests -B clean package native-image:native-image --file pom.xml
      - name: Move artifacts
        run: mkdir target/mac-native && mv target/sockiopath*runner target/mac-native
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: mac-native
          path: target/mac-native
