name: GraalVM Native Image build

on:
  push:
    branches: [ main ]
    tags: [ '*' ]

jobs:
  buildOnLinux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: ayltai/setup-graalvm@v1
        with:
          java-version: 17
          graalvm-version: 22.2.0
          native-image: true
      - name: Build with Maven
        run: mvn -DskipTests -B clean install -Dnative --file pom.xml
      - name: Run UPX
        uses: crazy-max/ghaction-upx@v1.3.3
        with:
          version: latest
          file: target/demo-cli
          args: '-7'
      - name: Upload artifacts
        run: mkdir staging && cp target/demo-cli staging/demo-cli-linux-amd64
      - uses: actions/upload-artifact@v2
        with:
          name: package
          path: staging