name: GraalVM Native Image build

on:
  push:
    branches: [ main ]
    tags: [ '*' ]

jobs:
  buildOnLinux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: ayltai/setup-graalvm@v1
        with:
          java-version: 17
          graalvm-version: 22.2.0
          native-image: true
      - name: Build with Maven
        run: mvn -B clean install -Dnative --file pom.xml
      - name: Move artifacts
        run: mkdir target/native && mv target/sockiopath*runner target/native
      - name: Run UPX
        uses: crazy-max/ghaction-upx@v1.3.3
        with:
          version: latest
          file: target/native
          args: '-7'
      - name: Upload artifacts
        run: mkdir staging && cp -r target/native staging/native
      - uses: actions/upload-artifact@v2
        with:
          name: package
          path: staging