## This is basic continuous integration build for your Quarkus application.

name: Quarkus Codestart CI

on:
  pull_request:
    branches: [ main ]

jobs:
  coverage:
    runs-on: ubuntu-latest
    environment: deploying
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'
          cache: 'maven'
      - name: Verify
        run: ./mvnw -B verify --file pom.xml
  report:
    runs-on: ubuntu-latest
    environment: deploying
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'
      - name: Checkstyle
        run: ./mvnw -B checkstyle:checkstyle
      - name: Archive checkstyle report
        uses: actions/upload-artifact@v3
        with:
          name: checkstyle-report
          path: target/site

